"""Install a dark theme override so the Power Chart's plot area is not white.

WHY THIS EXISTS

The Power Chart draws its plot surface as an SVG `<rect class="ia_chartRow__background">`
with `fill: white`, and NEITHER shipped theme changes it -- confirmed by grepping
`dark.css` and `light.css` for `chartRow__background` and finding nothing. So a
dark page gets a bright white rectangle in the middle of every chart, and no
combination of view.json props fixes it: it is CSS, not a component prop.

A browser dark-mode extension does not fix it either. Extensions invert page
colours, but an SVG `fill` attribute is not something they reliably touch --
which is exactly why the plot kept looking light-grey in screenshots of an
otherwise dark page.

HOW, AND WHY THIS WAY

Straight from the vendor's own README in the themes directory:

  "Overriding or adapting themes is easy ... Simply add your own CSS import
   pointing to your own custom style sheet containing the rulesets that you
   want to override or adapt AFTER any existing imports."

and, importantly:

  "any changes to the `light` and `dark` FOLDERS will be discarded on startup
   ... Note, changes to `light.css` and `dark.css` ENTRY POINTS will not be
   discarded on startup"

So this writes a new file under `themes/custom/` and appends one `@import` to
the `dark.css` entry point. Nothing inside the IA-owned `dark/` folder is
touched, so nothing here is discarded on restart.

Every selector below was read off the live rendered DOM, not guessed:

    .ia_chartRow__background                        <rect>  fill white
    .ia_powerChartComponent__yAxis__values          <g>
    .ia_powerChartComponent__yAxis__ticks           <line>
    .ia_powerChartComponent__yAxis__axis            <line>
    .ia_powerChartComponent__timeAxis__values       <g>
    .ia_powerChartComponent__timeAxis__ticks        <line>
    .ia_powerChartComponent__timeAxis__axis         <line>

SCOPE WARNING: the themes directory is GATEWAY-WIDE, not per-project. Every
Perspective project on this gateway that uses the dark theme gets these rules.
On a lab gateway that is fine; on a shared one, make a custom theme entry
(mytheme.css) instead and point only this project's session at it.

Usage:
    python scripts/install_theme.py --container 81-GW1-1
    python scripts/install_theme.py --container 81-GW2-1 --restart
"""
import argparse
import json
import subprocess
import sys

THEMES = ("/usr/local/bin/ignition/data/modules/"
          "com.inductiveautomation.perspective/themes")
CUSTOM_DIR = THEMES + "/custom"
CUSTOM_FILE = CUSTOM_DIR + "/gateway-health.css"
ENTRY = THEMES + "/dark.css"
IMPORT_LINE = '@import "./custom/gateway-health.css";'

SESSION_PROPS = ("/usr/local/bin/ignition/data/projects/%s/"
                 "com.inductiveautomation.perspective/session-props/props.json")

# Surfaces match the tile cards the view script builds, so the charts read as
# part of the same page rather than as embedded white boxes.
CSS = """/* gateway-thread-monitor: dark plot surfaces for the Power Chart.
 *
 * Generated by scripts/install_theme.py. Selectors were read off the live
 * rendered DOM. See that script's docstring for why this cannot be done with
 * component props.
 */

/* The plot surface itself. This is the whole reason the file exists: the
 * component hard-codes fill:white and no shipped theme overrides it.
 *
 * !important is REQUIRED and is not laziness. The component writes an INLINE
 * style attribute -- style="fill: rgb(255, 255, 255);" -- straight onto the
 * rect, and an inline style beats any class selector. Verified in the live
 * DOM: without !important this rule loads and loses silently, while the
 * neighbouring stroke rules (which have no inline equivalent) apply fine.
 * That asymmetry is exactly what made it look like the CSS "wasn't loading". */
.ia_chartRow__background {
    fill: #1A1F28 !important;
}

/* Axis lines: present but recessive. On a dark surface a mid-grey axis reads
 * as loud, so these sit only just above the panel colour. */
.ia_powerChartComponent__yAxis__axis,
.ia_powerChartComponent__timeAxis__axis,
.ia_powerChartComponent__yAxis__ticks,
.ia_powerChartComponent__timeAxis__ticks {
    stroke: #2E3641 !important;
}

/* Tick numbers and time labels. Readable, never competing with the traces. */
/* Same story: these carry style="fill: rgb(117, 122, 127)" inline. */
.ia_powerChartComponent__yAxis__values,
.ia_powerChartComponent__timeAxis__values,
.ia_powerChartComponent__yAxis__label {
    fill: #8B94A3 !important;
}

/* The chart chrome around the plot -- header bar, option bar, date selector --
 * so the panel does not sit on a pale strip. */
.ia_powerChartComponent,
.ia_powerChartComponent__chartOptionBar,
.ia_powerChartComponent__dateTimeSelection {
    background-color: #12161C;
}
"""


# --- 8.3 layout -----------------------------------------------------------
#
# 8.3 moved themes out of data/modules and into the config resource store:
#   data/config/resources/core/com.inductiveautomation.perspective/themes/
# and it MIGRATES anything found at the old path on startup (it left a
# .migrated-themes-<timestamp>/ folder behind proving it). So writing to the
# 8.1 location on an 8.3 gateway silently does nothing useful.
#
# There, a theme is a FOLDER with config.json {"entrypoint","isPrivate"} and an
# index.css. `dark` and `light` are not folders on disk -- they live in the
# module -- but the shipped derivative themes import from them by relative
# path, so those paths resolve.
#
# The import list below is copied verbatim from the shipped `dark-cool` theme's
# index.css, with its own variables.css swapped for dark's. That is the
# vendor's own recipe for "a dark theme plus my changes", which makes this a
# derived file rather than an invented one.
THEMES_83 = ("/usr/local/bin/ignition/data/config/resources/core/"
             "com.inductiveautomation.perspective/themes")
CUSTOM_THEME_83 = "gatewayHealthDark"

INDEX_83 = """/* gateway-thread-monitor: the dark theme, plus dark chart surfaces.
 *
 * Import list taken from the shipped dark-cool theme's index.css, which is
 * the vendor's own example of extending a built-in theme.
 */
@import "../dark/variables.css";
@import "../light/fonts.css";
@import "../dark/globals.css";
@import "../light/app/index.css";
@import "../light/common/index.css";
@import "../light/designer/index.css";
@import "../light/palette/index.css";
@import "../dark/palette/index.css";
@import "./gateway-health.css";
"""

CONFIG_83 = '{\n  "entrypoint": "index.css",\n  "isPrivate": false\n}\n'


def is_83(container):
    probe = run(container, "test -d '%s' && echo yes" % (THEMES_83,))
    return "yes" in probe.stdout


def install_83(container):
    """Create a derived theme folder, because 8.3 discards edits to dark."""
    folder = "%s/%s" % (THEMES_83, CUSTOM_THEME_83)
    run(container, "mkdir -p '%s'" % (folder,))
    put(container, folder + "/gateway-health.css", CSS)
    put(container, folder + "/index.css", INDEX_83)
    put(container, folder + "/config.json", CONFIG_83)
    print("  wrote theme '%s' (8.3 resource layout)" % (CUSTOM_THEME_83,))
    return CUSTOM_THEME_83


def run(container, script):
    return subprocess.run(["docker", "exec", container, "sh", "-c", script],
                          capture_output=True, text=True, errors="replace")


def put(container, remote, content):
    proc = subprocess.Popen(["docker", "exec", "-i", container, "sh", "-c",
                             "cat > '%s'" % (remote,)], stdin=subprocess.PIPE)
    proc.communicate(content.encode("utf-8"))
    if proc.returncode != 0:
        raise SystemExit("failed writing %s" % (remote,))


def install_css(container):
    run(container, "mkdir -p '%s'" % (CUSTOM_DIR,))
    put(container, CUSTOM_FILE, CSS)

    entry = run(container, "cat '%s' 2>/dev/null" % (ENTRY,)).stdout
    if IMPORT_LINE in entry:
        print("  dark.css already imports the override")
        return False
    # Appended AFTER the existing imports, which is what makes it win.
    put(container, ENTRY, entry.rstrip("\n") + "\n" + IMPORT_LINE + "\n")
    print("  appended the import to dark.css")
    return True


def set_theme(container, project, theme):
    """Point the project's session at the dark theme.

    The themes README states it plainly: "A project's active theme is defined
    in a project's session properties." Without this the project renders on
    the default light theme -- which is what made a browser dark-mode
    extension look like the only thing making the page dark.
    """
    remote = SESSION_PROPS % (project,)
    raw = run(container, "cat '%s'" % (remote,)).stdout
    if not raw.strip():
        print("  no session-props found; skipping theme")
        return False
    data = json.loads(raw)
    props = data.setdefault("props", {})
    if props.get("theme") == theme:
        print("  session theme already %s" % (theme,))
        return False
    props["theme"] = theme
    put(container, remote, json.dumps(data, indent=2) + "\n")
    print("  set session theme to %s" % (theme,))
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--container", required=True)
    parser.add_argument("--project",
                        default="Gateway_Thread_Pool_Analyzer_and_Historizer")
    parser.add_argument("--theme", default="dark")
    parser.add_argument("--restart", action="store_true",
                        help="restart afterwards (needed on 8.3)")
    args = parser.parse_args()

    print("%s:" % (args.container,))
    if is_83(args.container):
        theme = install_83(args.container)
    else:
        install_css(args.container)
        theme = args.theme
    set_theme(args.container, args.project, theme)

    if args.restart:
        subprocess.check_call(["docker", "restart", args.container],
                              stdout=subprocess.DEVNULL)
        print("  restarted")
    else:
        print("  theme changes are picked up on the next session load; "
              "session-props may need a gateway restart")
    return 0


if __name__ == "__main__":
    sys.exit(main())
